name: 'composer install'
description: 'Install composer dependencies for testing'
inputs:
  php_version:
    description: 'PHP version to use'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '${{ inputs.php_version }}'
        extensions: intl zip

    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer

    - name: Install dependencies
      shell: bash
      run: composer install --prefer-dist
