---
name: Code Climate coverage

on:
  workflow_call:
    inputs:
      php-version-main:
        description: 'Main PHP version'
        required: false
        default: '8.3'
        type: string
    secrets:
      CC_TEST_REPORTER_ID:
        description: 'Code Climate Test Reporter ID'
        required: true

jobs:
  'coverage-phpunit':
    name: 'Test coverage by Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astehlik/typo3-extension-buildtools/actions/composer@TYPO3_13
        with:
          php_version: ${{ inputs.php-version-main }}
      - run: |
          bash bin/t3_run_tests.sh -s unit -p ${{ inputs.php-version-main }} -X coverage -- --coverage-clover Logs/clover-unit.xml --coverage-filter ../Classes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-phpunit
          path: Logs/clover-unit.xml
          retention-days: 1

  'coverage-functional':
    name: 'Test coverage by Functional Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astehlik/typo3-extension-buildtools/actions/composer@TYPO3_13
        with:
          php_version: ${{ inputs.php-version-main }}
      - run: |
          bash bin/t3_run_tests.sh -s functional -d mariadb -p ${{ inputs.php-version-main }} -X coverage -- --coverage-clover Logs/clover-functional.xml --coverage-filter ../Classes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-functional
          path: Logs/clover-functional.xml
          retention-days: 1

  'coverage-upload':
    name: Upload coverage report to Code Climage
    needs:
      - coverage-phpunit
      - coverage-functional
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: coverage-phpunit
      - uses: actions/download-artifact@v4
        with:
          name: coverage-functional
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: |
          ./cc-test-reporter format-coverage -t clover -o clover-unit.json clover-unit.xml
      - run: |
          ./cc-test-reporter format-coverage -t clover -o clover-functional.json clover-functional.xml
      - run: |
          ./cc-test-reporter sum-coverage --parts=2 --output=clover-sum.json clover-unit.json clover-functional.json
      - run: |
          ./cc-test-reporter upload-coverage --input=clover-sum.json
