---
name: Qlty coverage

on:
  workflow_call:
    inputs:
      php-version-main:
        description: 'Main PHP version'
        required: false
        default: '8.4'
        type: string
    secrets:
      QLTY_COVERAGE_TOKEN:
        description: 'Qlty Coverage Token'
        required: true

jobs:
  'coverage-phpunit':
    name: 'Test coverage by Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astehlik/typo3-extension-buildtools/actions/composer@TYPO3_13
        with:
          php_version: ${{ inputs.php-version-main }}
      - run: |
          bash bin/t3_run_tests.sh -s unit -p ${{ inputs.php-version-main }} -X coverage -- --coverage-clover Logs/clover-unit.xml --coverage-filter ../Classes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-phpunit
          path: Logs/clover-unit.xml
          retention-days: 1

  'coverage-functional':
    name: 'Test coverage by Functional Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astehlik/typo3-extension-buildtools/actions/composer@TYPO3_13
        with:
          php_version: ${{ inputs.php-version-main }}
      - run: |
          bash bin/t3_run_tests.sh -s functional -d mariadb -b docker -p ${{ inputs.php-version-main }} -X coverage -- --coverage-clover Logs/clover-functional.xml --coverage-filter ../Classes
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-functional
          path: Logs/clover-functional.xml
          retention-days: 1

  'coverage-upload':
    name: Upload coverage report to Qlty
    needs:
      - coverage-phpunit
      - coverage-functional
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: coverage-phpunit
      - uses: actions/download-artifact@v4
        with:
          name: coverage-functional
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: clover-*.xml
