name: Lint

on:
  push:
    branches:
      - TYPO3_13
      - TYPO3_14

permissions:
  contents: read

jobs:
  lint-composer:
    name: 'Lint composer.json'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./actions/composer
        with:
          php_version: 8.4
      - run: composer validate
      - run: composer normalize --dry-run --diff

  lint-prettier:
    name: 'Lint prettier'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install
      - run: npx prettier --check .

  lint-php-cs-fixer:
    name: 'Lint PHP CS Fixer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./actions/composer
        with:
          php_version: 8.2
      - run: composer install
      - run: vendor/bin/php-cs-fixer fix --dry-run --diff --config=build/php-cs-fixer/config.php

  lint-github-actions:
    name: 'Lint GitHub Actions with zizmor'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
